package com.misterveiga.cds.utils.enums;

public enum CDSRole {
	ROLE_LEAD, ROLE_SERVER_MANAGER, ROLE_SENIOR_COMMUNITY_SUPERVISOR, ROLE_COMMUNITY_SUPERVISOR, ROLE_TRIAL_SUPERVISOR,
	ROLE_PUBLIC_SECTOR, ROLE_INFRASTRUCTURE
}
