package com.misterveiga.cds.utils.enums;

public enum CDSRole {
	ROLE_LEAD, ROLE_SERVER_MANAGER, ROLE_SENIOR_MODERATOR, ROLE_MODERATOR, ROLE_TRIAL_MODERATOR,
	ROLE_PUBLIC_SECTOR, ROLE_INFRASTRUCTURE
}
